name: Run Twitter Bot

on:
  schedule:
    # Runs approximately every 90 minutes (1.5 hours).
    # Standard cron doesn't support intervals like 'every 95 minutes',
    # so this is the closest reliable schedule.
    - cron: '0 0,3,6,9,12,15,18,21 * * *'
    - cron: '30 1,4,7,10,13,16,19,22 * * *'
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Twitter Bot
        run: node index.js
